<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function shp_share_node_presave(NodeInterface $node): void {
  if ($node->bundle() === 'bag') {
    $bag = $node;
    $groups = \Drupal::entityTypeManager()
      ->getStorage('group')
      ->loadByProperties([
        'type' => 'bag_members',
        'field_bag' => $bag->id(),
        'status' => 1,
      ]);

    if (!empty($groups)) {
      return;
    }

    $group = \Drupal::entityTypeManager()
      ->getStorage('group')
      ->create([
        'type' => 'bag_members',
        'label' => $bag->label(),
        'field_bag' => $bag->id(),
        'status' => 1,
      ]);

    $group->save();
  }
}
