_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  anonymous_token: 0
  automated_cron: 0
  backup_migrate: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  coffee: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  flexible_permissions: 0
  gin_toolbar: 0
  group: 0
  help: 0
  history: 0
  image: 0
  layout_builder: 0
  layout_builder_expose_all_field_blocks: 0
  layout_discovery: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  one_time_login_link_admin: 0
  options: 0
  page_cache: 0
  paragraphs_gridstack: 0
  path: 0
  path_alias: 0
  phpass: 0
  pwa: 0
  pwa_a2hs: 0
  pwa_extras: 0
  pwa_service_worker: 0
  search: 0
  shield: 0
  shortcut: 0
  shp_access: 0
  shp_share: 0
  statistics: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_infinite_scroll: 0
  views_ui: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  olivero_shopper_io: 0
  gin: 0
profile: standard
