_core:
  default_config_hash: cP1TZQyv1WdET3iepl2QoyOPK7VeO0xHm0lU_FU1Wmc
short_name: Shopper.io
description: ''
start_url: /bags
lang: en
theme_color: '#2494db'
background_color: '#f7f9fa'
display: fullscreen
cross_origin: false
site_name: 'Shopper.io - Create&Share shopping lists'
default_image: '0'
urls_to_cache: "/\r\n/bags\r\n/shared-with-you\r\n/starred"
urls_to_exclude: "admin/.*\r\nuser/.*"
offline_page: /offline
cache_version: '2'
skip_waiting: false
image: /sites/default/files/pwa/shopping_bag_icon_192682_512_512.png
image_small: /sites/default/files/pwa/shopping_bag_icon_192682_512_512.pngcopy.png
image_very_small: /sites/default/files/pwa/shopping_bag_icon_192682_512_512.pngcopy2.png
